name: tri-bench
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - openpyxl
    - openai
    - python-dotenv
    - pandas
    - numpy
    - tqdm
    - requests
    - retrying
    
# conda env create -f environment.yml
# conda env update -f environment.yml